/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polycat.tool.migration.entity;

import java.io.Serializable;
import java.util.Date;

public class MigrationItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.migration_id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Integer migrationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.type
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.item_name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.start_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.end_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.status
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.properties
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String properties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration_item.extra
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table migration_item
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.id
     *
     * @return the value of migration_item.id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.id
     *
     * @param id the value for migration_item.id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.migration_id
     *
     * @return the value of migration_item.migration_id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Integer getMigrationId() {
        return migrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.migration_id
     *
     * @param migrationId the value for migration_item.migration_id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setMigrationId(Integer migrationId) {
        this.migrationId = migrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.type
     *
     * @return the value of migration_item.type
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.type
     *
     * @param type the value for migration_item.type
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.item_name
     *
     * @return the value of migration_item.item_name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.item_name
     *
     * @param itemName the value for migration_item.item_name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.start_time
     *
     * @return the value of migration_item.start_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.start_time
     *
     * @param startTime the value for migration_item.start_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.end_time
     *
     * @return the value of migration_item.end_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.end_time
     *
     * @param endTime the value for migration_item.end_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.status
     *
     * @return the value of migration_item.status
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.status
     *
     * @param status the value for migration_item.status
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.properties
     *
     * @return the value of migration_item.properties
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.properties
     *
     * @param properties the value for migration_item.properties
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setProperties(String properties) {
        this.properties = properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration_item.extra
     *
     * @return the value of migration_item.extra
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration_item.extra
     *
     * @param extra the value for migration_item.extra
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration_item
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", migrationId=").append(migrationId);
        sb.append(", type=").append(type);
        sb.append(", itemName=").append(itemName);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", status=").append(status);
        sb.append(", properties=").append(properties);
        sb.append(", extra=").append(extra);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}