/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polycat.tool.migration.entity;

import java.io.Serializable;
import java.util.Date;

public class Migration implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.source_uri
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String sourceUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.source_user
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String sourceUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.source_password
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String sourcePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.dest_uri
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String destUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.dest_user
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String destUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.dest_password
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String destPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.project_id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.tenant_name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String tenantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.status
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.create_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.sync_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private Date syncTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column migration.extra
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private String extra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.id
     *
     * @return the value of migration.id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.id
     *
     * @param id the value for migration.id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.name
     *
     * @return the value of migration.name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.name
     *
     * @param name the value for migration.name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.source_uri
     *
     * @return the value of migration.source_uri
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getSourceUri() {
        return sourceUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.source_uri
     *
     * @param sourceUri the value for migration.source_uri
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setSourceUri(String sourceUri) {
        this.sourceUri = sourceUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.source_user
     *
     * @return the value of migration.source_user
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getSourceUser() {
        return sourceUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.source_user
     *
     * @param sourceUser the value for migration.source_user
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setSourceUser(String sourceUser) {
        this.sourceUser = sourceUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.source_password
     *
     * @return the value of migration.source_password
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getSourcePassword() {
        return sourcePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.source_password
     *
     * @param sourcePassword the value for migration.source_password
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setSourcePassword(String sourcePassword) {
        this.sourcePassword = sourcePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.dest_uri
     *
     * @return the value of migration.dest_uri
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getDestUri() {
        return destUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.dest_uri
     *
     * @param destUri the value for migration.dest_uri
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setDestUri(String destUri) {
        this.destUri = destUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.dest_user
     *
     * @return the value of migration.dest_user
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getDestUser() {
        return destUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.dest_user
     *
     * @param destUser the value for migration.dest_user
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setDestUser(String destUser) {
        this.destUser = destUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.dest_password
     *
     * @return the value of migration.dest_password
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getDestPassword() {
        return destPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.dest_password
     *
     * @param destPassword the value for migration.dest_password
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setDestPassword(String destPassword) {
        this.destPassword = destPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.project_id
     *
     * @return the value of migration.project_id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.project_id
     *
     * @param projectId the value for migration.project_id
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.tenant_name
     *
     * @return the value of migration.tenant_name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getTenantName() {
        return tenantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.tenant_name
     *
     * @param tenantName the value for migration.tenant_name
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.status
     *
     * @return the value of migration.status
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.status
     *
     * @param status the value for migration.status
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.create_time
     *
     * @return the value of migration.create_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.create_time
     *
     * @param createTime the value for migration.create_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.sync_time
     *
     * @return the value of migration.sync_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Date getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.sync_time
     *
     * @param syncTime the value for migration.sync_time
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column migration.extra
     *
     * @return the value of migration.extra
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column migration.extra
     *
     * @param extra the value for migration.extra
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sourceUri=").append(sourceUri);
        sb.append(", sourceUser=").append(sourceUser);
        sb.append(", sourcePassword=").append(sourcePassword);
        sb.append(", destUri=").append(destUri);
        sb.append(", destUser=").append(destUser);
        sb.append(", destPassword=").append(destPassword);
        sb.append(", projectId=").append(projectId);
        sb.append(", tenantName=").append(tenantName);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", syncTime=").append(syncTime);
        sb.append(", extra=").append(extra);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}