/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.polycat.tool.migration.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MigrationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public MigrationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSourceUriIsNull() {
            addCriterion("source_uri is null");
            return (Criteria) this;
        }

        public Criteria andSourceUriIsNotNull() {
            addCriterion("source_uri is not null");
            return (Criteria) this;
        }

        public Criteria andSourceUriEqualTo(String value) {
            addCriterion("source_uri =", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriNotEqualTo(String value) {
            addCriterion("source_uri <>", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriGreaterThan(String value) {
            addCriterion("source_uri >", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriGreaterThanOrEqualTo(String value) {
            addCriterion("source_uri >=", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriLessThan(String value) {
            addCriterion("source_uri <", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriLessThanOrEqualTo(String value) {
            addCriterion("source_uri <=", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriLike(String value) {
            addCriterion("source_uri like", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriNotLike(String value) {
            addCriterion("source_uri not like", value, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriIn(List<String> values) {
            addCriterion("source_uri in", values, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriNotIn(List<String> values) {
            addCriterion("source_uri not in", values, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriBetween(String value1, String value2) {
            addCriterion("source_uri between", value1, value2, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUriNotBetween(String value1, String value2) {
            addCriterion("source_uri not between", value1, value2, "sourceUri");
            return (Criteria) this;
        }

        public Criteria andSourceUserIsNull() {
            addCriterion("source_user is null");
            return (Criteria) this;
        }

        public Criteria andSourceUserIsNotNull() {
            addCriterion("source_user is not null");
            return (Criteria) this;
        }

        public Criteria andSourceUserEqualTo(String value) {
            addCriterion("source_user =", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserNotEqualTo(String value) {
            addCriterion("source_user <>", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserGreaterThan(String value) {
            addCriterion("source_user >", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserGreaterThanOrEqualTo(String value) {
            addCriterion("source_user >=", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserLessThan(String value) {
            addCriterion("source_user <", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserLessThanOrEqualTo(String value) {
            addCriterion("source_user <=", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserLike(String value) {
            addCriterion("source_user like", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserNotLike(String value) {
            addCriterion("source_user not like", value, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserIn(List<String> values) {
            addCriterion("source_user in", values, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserNotIn(List<String> values) {
            addCriterion("source_user not in", values, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserBetween(String value1, String value2) {
            addCriterion("source_user between", value1, value2, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourceUserNotBetween(String value1, String value2) {
            addCriterion("source_user not between", value1, value2, "sourceUser");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordIsNull() {
            addCriterion("source_password is null");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordIsNotNull() {
            addCriterion("source_password is not null");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordEqualTo(String value) {
            addCriterion("source_password =", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordNotEqualTo(String value) {
            addCriterion("source_password <>", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordGreaterThan(String value) {
            addCriterion("source_password >", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("source_password >=", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordLessThan(String value) {
            addCriterion("source_password <", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordLessThanOrEqualTo(String value) {
            addCriterion("source_password <=", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordLike(String value) {
            addCriterion("source_password like", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordNotLike(String value) {
            addCriterion("source_password not like", value, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordIn(List<String> values) {
            addCriterion("source_password in", values, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordNotIn(List<String> values) {
            addCriterion("source_password not in", values, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordBetween(String value1, String value2) {
            addCriterion("source_password between", value1, value2, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andSourcePasswordNotBetween(String value1, String value2) {
            addCriterion("source_password not between", value1, value2, "sourcePassword");
            return (Criteria) this;
        }

        public Criteria andDestUriIsNull() {
            addCriterion("dest_uri is null");
            return (Criteria) this;
        }

        public Criteria andDestUriIsNotNull() {
            addCriterion("dest_uri is not null");
            return (Criteria) this;
        }

        public Criteria andDestUriEqualTo(String value) {
            addCriterion("dest_uri =", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriNotEqualTo(String value) {
            addCriterion("dest_uri <>", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriGreaterThan(String value) {
            addCriterion("dest_uri >", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriGreaterThanOrEqualTo(String value) {
            addCriterion("dest_uri >=", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriLessThan(String value) {
            addCriterion("dest_uri <", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriLessThanOrEqualTo(String value) {
            addCriterion("dest_uri <=", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriLike(String value) {
            addCriterion("dest_uri like", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriNotLike(String value) {
            addCriterion("dest_uri not like", value, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriIn(List<String> values) {
            addCriterion("dest_uri in", values, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriNotIn(List<String> values) {
            addCriterion("dest_uri not in", values, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriBetween(String value1, String value2) {
            addCriterion("dest_uri between", value1, value2, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUriNotBetween(String value1, String value2) {
            addCriterion("dest_uri not between", value1, value2, "destUri");
            return (Criteria) this;
        }

        public Criteria andDestUserIsNull() {
            addCriterion("dest_user is null");
            return (Criteria) this;
        }

        public Criteria andDestUserIsNotNull() {
            addCriterion("dest_user is not null");
            return (Criteria) this;
        }

        public Criteria andDestUserEqualTo(String value) {
            addCriterion("dest_user =", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserNotEqualTo(String value) {
            addCriterion("dest_user <>", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserGreaterThan(String value) {
            addCriterion("dest_user >", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserGreaterThanOrEqualTo(String value) {
            addCriterion("dest_user >=", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserLessThan(String value) {
            addCriterion("dest_user <", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserLessThanOrEqualTo(String value) {
            addCriterion("dest_user <=", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserLike(String value) {
            addCriterion("dest_user like", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserNotLike(String value) {
            addCriterion("dest_user not like", value, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserIn(List<String> values) {
            addCriterion("dest_user in", values, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserNotIn(List<String> values) {
            addCriterion("dest_user not in", values, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserBetween(String value1, String value2) {
            addCriterion("dest_user between", value1, value2, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestUserNotBetween(String value1, String value2) {
            addCriterion("dest_user not between", value1, value2, "destUser");
            return (Criteria) this;
        }

        public Criteria andDestPasswordIsNull() {
            addCriterion("dest_password is null");
            return (Criteria) this;
        }

        public Criteria andDestPasswordIsNotNull() {
            addCriterion("dest_password is not null");
            return (Criteria) this;
        }

        public Criteria andDestPasswordEqualTo(String value) {
            addCriterion("dest_password =", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordNotEqualTo(String value) {
            addCriterion("dest_password <>", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordGreaterThan(String value) {
            addCriterion("dest_password >", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("dest_password >=", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordLessThan(String value) {
            addCriterion("dest_password <", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordLessThanOrEqualTo(String value) {
            addCriterion("dest_password <=", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordLike(String value) {
            addCriterion("dest_password like", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordNotLike(String value) {
            addCriterion("dest_password not like", value, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordIn(List<String> values) {
            addCriterion("dest_password in", values, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordNotIn(List<String> values) {
            addCriterion("dest_password not in", values, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordBetween(String value1, String value2) {
            addCriterion("dest_password between", value1, value2, "destPassword");
            return (Criteria) this;
        }

        public Criteria andDestPasswordNotBetween(String value1, String value2) {
            addCriterion("dest_password not between", value1, value2, "destPassword");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andTenantNameIsNull() {
            addCriterion("tenant_name is null");
            return (Criteria) this;
        }

        public Criteria andTenantNameIsNotNull() {
            addCriterion("tenant_name is not null");
            return (Criteria) this;
        }

        public Criteria andTenantNameEqualTo(String value) {
            addCriterion("tenant_name =", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameNotEqualTo(String value) {
            addCriterion("tenant_name <>", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameGreaterThan(String value) {
            addCriterion("tenant_name >", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_name >=", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameLessThan(String value) {
            addCriterion("tenant_name <", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameLessThanOrEqualTo(String value) {
            addCriterion("tenant_name <=", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameLike(String value) {
            addCriterion("tenant_name like", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameNotLike(String value) {
            addCriterion("tenant_name not like", value, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameIn(List<String> values) {
            addCriterion("tenant_name in", values, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameNotIn(List<String> values) {
            addCriterion("tenant_name not in", values, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameBetween(String value1, String value2) {
            addCriterion("tenant_name between", value1, value2, "tenantName");
            return (Criteria) this;
        }

        public Criteria andTenantNameNotBetween(String value1, String value2) {
            addCriterion("tenant_name not between", value1, value2, "tenantName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeIsNull() {
            addCriterion("sync_time is null");
            return (Criteria) this;
        }

        public Criteria andSyncTimeIsNotNull() {
            addCriterion("sync_time is not null");
            return (Criteria) this;
        }

        public Criteria andSyncTimeEqualTo(Date value) {
            addCriterion("sync_time =", value, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeNotEqualTo(Date value) {
            addCriterion("sync_time <>", value, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeGreaterThan(Date value) {
            addCriterion("sync_time >", value, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sync_time >=", value, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeLessThan(Date value) {
            addCriterion("sync_time <", value, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeLessThanOrEqualTo(Date value) {
            addCriterion("sync_time <=", value, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeIn(List<Date> values) {
            addCriterion("sync_time in", values, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeNotIn(List<Date> values) {
            addCriterion("sync_time not in", values, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeBetween(Date value1, Date value2) {
            addCriterion("sync_time between", value1, value2, "syncTime");
            return (Criteria) this;
        }

        public Criteria andSyncTimeNotBetween(Date value1, Date value2) {
            addCriterion("sync_time not between", value1, value2, "syncTime");
            return (Criteria) this;
        }

        public Criteria andExtraIsNull() {
            addCriterion("extra is null");
            return (Criteria) this;
        }

        public Criteria andExtraIsNotNull() {
            addCriterion("extra is not null");
            return (Criteria) this;
        }

        public Criteria andExtraEqualTo(String value) {
            addCriterion("extra =", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotEqualTo(String value) {
            addCriterion("extra <>", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThan(String value) {
            addCriterion("extra >", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraGreaterThanOrEqualTo(String value) {
            addCriterion("extra >=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThan(String value) {
            addCriterion("extra <", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLessThanOrEqualTo(String value) {
            addCriterion("extra <=", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraLike(String value) {
            addCriterion("extra like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotLike(String value) {
            addCriterion("extra not like", value, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraIn(List<String> values) {
            addCriterion("extra in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotIn(List<String> values) {
            addCriterion("extra not in", values, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraBetween(String value1, String value2) {
            addCriterion("extra between", value1, value2, "extra");
            return (Criteria) this;
        }

        public Criteria andExtraNotBetween(String value1, String value2) {
            addCriterion("extra not between", value1, value2, "extra");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table migration
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 14 14:33:10 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table migration
     *
     * @mbg.generated Mon Feb 14 14:33:10 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}