FROM ubuntu:18.04
MAINTAINER polycat_developer

# update ubuntu sources
RUN mv /etc/apt/sources.list  /etc/apt/sources.list_bak
ADD ./target/sources.list /etc/apt/sources.list

# install vim
RUN apt-get update -y && apt-get install -y vim curl wget git lsof net-tools iputils-ping iproute2

# install jre
ADD ./target/jre/jre-8u301-linux-x64.tar.gz /opt/jre/
ENV JAVA_HOME=/opt/jre/jre1.8.0_301
ENV CLASSPATH=$JAVA_HOME/lib
ENV PATH=$PATH:$JAVA_HOME/bin

# install foundationdb client
#COPY ./target/foundationdb /opt/foundationdb
#RUN dpkg -i /opt/foundationdb/foundationdb-clients_6.3.15-1_amd64.deb

# install dash
ADD ./target/polycat-catalog-0.1-SNAPSHOT.tar.gz /opt/dash/

# start catalog
ENTRYPOINT bash /opt/dash/polycat-catalog/bin/catalog.sh