{
 "title": "system performance dashboard",
 "time": { "from": "2021-08-05T08:55:57.225Z", "to": "2021-08-05T08:56:13.509Z" },
 "refresh": "1s",
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "success sql count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sql_server_seconds_count{status=\"success\"})",
     "legendFormat": "success sql count"
    }
   ]
  },
  {
   "title": "fail sql count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sql_server_seconds_count{status=\"fail\"})",
     "legendFormat": "fail sql count"
    }
   ]
  },
  {
   "title": "catalog rest api count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri!~\"/actuator.*\"})",
     "legendFormat": "catalog rest api count"
    }
   ]
  },
  {
   "title": "classified rest api count",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri!~\"/actuator.*\"}) by (method)"
    }
   ]
  },
  { "title": "服务黄金指标 - SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "sql 吞吐量 (一秒钟平均)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(sql_server_seconds_count{status=\"success\"}[1m])"
    }
   ]
  },
  {
   "title": "sql 错误率  (一秒钟平均)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(sql_server_seconds_count{status=\"fail\"}[1m])",
     "legendFormat": "fail throughput"
    }
   ]
  },
  {
   "title": "sql 请求平均耗时（一秒钟平均）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_server_seconds_sum[1m])) / sum(rate(sql_server_seconds_count[1m]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "sql 长尾时延分布（一分钟平均）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile( 0.5, sum(avg_over_time(sql_server_seconds_bucket[1s])) by (le) )",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile( 0.9, sum(avg_over_time(sql_server_seconds_bucket[1s])) by (le) )",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile( 0.95, sum(avg_over_time(sql_server_seconds_bucket[1s])) by (le) )",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile( 0.98, sum(avg_over_time(sql_server_seconds_bucket[1s])) by (le) )",
     "legendFormat": "P98"
    },
    {
     "expr": "histogram_quantile( 0.99, sum(avg_over_time(sql_server_seconds_bucket[1s])) by (le) )",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile( 0.999, sum(avg_over_time(sql_server_seconds_bucket[1s])) by (le) )",
     "legendFormat": "P999"
    }
   ]
  },
  { "title": "服务黄金指标 - Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "catalog 吞吐率 (一分钟平均)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "REST API"
    }
   ]
  },
  {
   "title": "catalog 错误率 (一分钟平均)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "http 5xx response"
    }
   ]
  },
  {
   "title": "请求平均时延（一分钟平均）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\", uri!=\"/actuator/prometheus\"}[1m]))/sum(rate(http_server_requests_seconds_count{status!~\"5..\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "AVG "
    },
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{status!~\"5..\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "MAX "
    }
   ]
  },
  {
   "title": "performance profiling 自定义",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "sql runtime breakdown overview (1秒内)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(sql_server_seconds_sum[1s])) / sum(avg_over_time(sql_server_seconds_count[1s]))",
       "legendFormat": "sql"
      },
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"prepare-stream\",phase=\"total\"}[1s]))",
       "legendFormat": "prepare_step_avg"
      },
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"running_stream\",phase=\"total\"}[1s]))",
       "legendFormat": "running_step_avg"
      }
     ]
    },
    {
     "title": "prepare-step breakdown (1秒内)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"prepare-stream\",phase=\"total\"}[1s]))",
       "legendFormat": "prepare avg"
      },
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"prepare-stream\",phase=\"compile\"}[1s]))",
       "legendFormat": "compile avg"
      },
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"prepare-stream\",phase=\"analyze\"}[1s]))",
       "legendFormat": "analyze avg"
      },
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"prepare-stream\",phase=\"optimize\"}[1s]))",
       "legendFormat": "optimize avg"
      },
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"prepare-stream\",phase=\"handleJob\"}[1s]))",
       "legendFormat": "handle job avg"
      }
     ]
    },
    {
     "title": "running-step breakdown (1秒内)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(sql_server_breakdown_seconds_sum{step=\"running_stream\",phase=\"total\"}[1s]))",
       "legendFormat": "running_step avg"
      },
      {
       "expr": "avg(avg_over_time({__name__=~\"jobId_._.*_SourceReadProcessor_.*_sum\", }[1s]))",
       "legendFormat": "source read"
      },
      {
       "expr": "avg(avg_over_time({__name__=~\"jobId_._.*_SourceWriteProcessor_.*_sum\", }[1s]))",
       "legendFormat": "source write"
      },
      {
       "expr": "avg(avg_over_time({__name__=~\"jobId_._.*_sum\", phase=\"SEND_DATA\"}[1s]))",
       "legendFormat": "send data"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\"}[1s]))/sum(rate(http_server_requests_seconds_count{status!~\"5..\"}[1s]))",
       "legendFormat": "meta data"
      },
      {
       "expr": "avg(avg_over_time({__name__!~\"jobId_._.*_CollectProcessor_.*_sum\", __name__!~\"jobId_._.*_ProducerTask_.*_sum\", __name__=~\"jobId_._.*_sum\"}[1s]))",
       "legendFormat": "processors"
      }
     ]
    }
   ]
  }
 ]
}