{
 "title": "runtime break down",
 "time": { "from": "2021-08-03T13:02:50.107Z", "to": "2021-08-03T13:05:39.322Z" },
 "panels": [
  {
   "title": "sql runtime overview",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sql_exec_overview_sum{jobId=~\".*\"}",
     "legendFormat": "total runtime"
    },
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"prepare-stream\", phase=\"total\"}",
     "legendFormat": "prepare-stream step time"
    },
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"running_stream\"}",
     "legendFormat": "running_stream step time"
    }
   ]
  },
  {
   "title": "prepare-step runtime breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"prepare-stream\", phase=\"total\"}",
     "legendFormat": "prepare-stream step time total"
    },
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"prepare-stream\", phase=\"compile\"}",
     "legendFormat": "compile"
    },
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"prepare-stream\", phase=\"analyze\"}",
     "legendFormat": "analyze"
    },
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"prepare-stream\", phase=\"optimize\"}",
     "legendFormat": "optimize"
    },
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"prepare-stream\", phase=\"handleJob\"}",
     "legendFormat": "handleJob"
    }
   ]
  },
  {
   "title": "prepare-step -> query handler runtime breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"6\", step=\"prepare-stream\", phase=\"handleJob\"}",
     "legendFormat": "handleJob total"
    },
    {
     "expr": "query_breakdown_job_id_6_sum{phase=\"build_DAG\"}",
     "legendFormat": "build_DAG"
    },
    {
     "expr": "query_breakdown_job_id_6_sum{phase=\"allocate_cores\"}",
     "legendFormat": "allocate_cores"
    },
    {
     "expr": "query_breakdown_job_id_6_sum{phase=\"build_stages\"}",
     "legendFormat": "build_stages"
    },
    {
     "expr": "query_breakdown_job_id_6_sum{phase=\"deploy_stages\"}",
     "legendFormat": "deploy_stages"
    }
   ]
  },
  {
   "title": "runing-step runtime breakdown",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sql_runtime_breakdown_sum{jobId=\"4\", step=\"running_stream\"}",
     "legendFormat": "running_stream step time total"
    },
    {
     "expr": "{__name__=~\"jobId_4_stageNo_0_.*_sum\", }",
     "legendFormat": "QueryHandler"
    },
    {
     "expr": "{__name__=~\"jobId_4_.*_CollectProcessor_.*_sum\",}",
     "legendFormat": "CollectProcessor"
    },
    {
     "expr": "{__name__=~\"jobId_4_.*_QueryHandler_.*_sum\", phase=\"PROCESS_INPUT\"}",
     "legendFormat": "WRITE_SEGMENT"
    },
    {
     "expr": "{__name__=~\"jobId_4_.*_sum\", phase=\"SEND_DATA\"}",
     "legendFormat": "SEND_DATA"
    },
    {
     "expr": "{__name__=~\"jobId_4_.*_SourceWriteProcessor_.*_sum\", phase=\"PROCESS_INPUT\"}",
     "legendFormat": "SourceWrite"
    },
    {
     "expr": "sum({__name__=~\"jobId_4_.*_SourceReadProcessor_.*_sum\", })",
     "legendFormat": "SourceRead"
    }
   ]
  }
 ]
}